### ISSUE TITLE
Multi-threading pyplot APIs causes issues

### ISSUE THREAD

**Issue by shaohua0116** [wookayin/tensorflow-plot#1]
This implementation includes showing histogram figures by calling plt.figure(). Here're the codes I ran: 
https://github.com/shaohua0116/Activation-Visualization-Histogram
I know that one way to deal with it is using object-oriented matplotlib APIs. And I first temporarily fixed it by setting *intra_op_parallelism_threads=1* and *inter_op_parallelism_threads=1* for tf.ConfigProto. If want to reproduce the errors, please simply comment the two lines:
https://github.com/shaohua0116/Activation-Visualization-Histogram/blob/master/trainer.py#L99
https://github.com/shaohua0116/Activation-Visualization-Histogram/blob/master/trainer.py#L100
and just run the trainer.py code. 
The error msgs are as following:

```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/tfplot/ops.py", line 61, in _render_image
    fig = plot_func(*args, **kwargs)
  File "/home/walter/task/Activations/model.py", line 111, in draw_act_hist
    n, bins, patches = plt.hist(np.reshape(h, [grid_shape[0]*grid_shape[1]]), 50, normed=1, facecolor='blue', alpha=0.75)
  File "/home/walter/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3067, in hist
    ax = gca()
  File "/home/walter/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)
  File "/home/walter/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 1368, in gca
    return self.add_subplot(1, 1, 1, **kwargs)
  File "/home/walter/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 1022, in add_subplot
    self._axstack.add(key, a)
  File "/home/walter/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 129, in add
    Stack.remove(self, (key, a_existing))
  File "/home/walter/.local/lib/python2.7/site-packages/matplotlib/cbook.py", line 1391, in remove
    raise ValueError('Unknown element o')
ValueError: Unknown element o
2017-06-10 19:59:27.837878: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_13: see error log.
2017-06-10 19:59:27.837998: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_13: see error log.
         [[Node: histogram/h5/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_INT64], Tout=[DT_UINT8], token="pyfunc_13", _device="/job:localhost/replica:0/task:0/cpu:0"](histogram/h5/Classifier/fully_connected_2/mul_1_unstack/_191, histogram/h5/Tile_5_unstack)]]
2017-06-10 19:59:27.840911: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_13: see error log.
         [[Node: histogram/h5/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_INT64], Tout=[DT_UINT8], token="pyfunc_13", _device="/job:localhost/replica:0/task:0/cpu:0"](histogram/h5/Classifier/fully_connected_2/mul_1_unstack/_191, histogram/h5/Tile_5_unstack)]]
2017-06-10 19:59:27.840978: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_13: see error log.
         [[Node: histogram/h5/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_INT64], Tout=[DT_UINT8], token="pyfunc_13", _device="/job:localhost/replica:0/task:0/cpu:0"](histogram/h5/Classifier/fully_connected_2/mul_1_unstack/_191, histogram/h5/Tile_5_unstack)]]
2017-06-10 19:59:27.841002: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_13: see error log.
         [[Node: histogram/h5/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_INT64], Tout=[DT_UINT8], token="pyfunc_13", _device="/job:localhost/replica:0/task:0/cpu:0"](histogram/h5/Classifier/fully_connected_2/mul_1_unstack/_191, histogram/h5/Tile_5_unstack)]]
Traceback (most recent call last):
  File "trainer.py", line 219, in <module>
    main()
  File "trainer.py", line 216, in main
    trainer.train()
  File "trainer.py", line 122, in train
    self.run_single_step(self.batch_train, step=s, is_train=True)
  File "trainer.py", line 148, in run_single_step
    feed_dict=self.model.get_feed_dict(batch_chunk, step=step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_13: see error log.
         [[Node: histogram/h5/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_INT64], Tout=[DT_UINT8], token="pyfunc_13", _device="/job:localhost/replica:0/task:0/cpu:0"](histogram/h5/Classifier/fully_connected_2/mul_1_unstack/_191, histogram/h5/Tile_5_unstack)]]
         [[Node: optimizer_loss/train/_202 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2337_optimizer_loss/train", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'histogram/h5/Plot_0', defined at:
  File "trainer.py", line 219, in <module>
    main()
  File "trainer.py", line 213, in main
    dataset_train, dataset_test)
  File "trainer.py", line 52, in __init__
    self.model = Model(config)
  File "/home/walter/task/Activations/model.py", line 46, in __init__
    self.build(is_train=is_train)
  File "/home/walter/task/Activations/model.py", line 127, in build
    collections=["plot_summaries"])
  File "/usr/local/lib/python2.7/dist-packages/tfplot/summary.py", line 78, in plot_many
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tfplot/ops.py", line 126, in plot_many
    im = plot(plot_func, arg, name=('Plot_%d' % k), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tfplot/ops.py", line 73, in plot
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_13: see error log.
         [[Node: histogram/h5/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_INT64], Tout=[DT_UINT8], token="pyfunc_13", _device="/job:localhost/replica:0/task:0/cpu:0"](histogram/h5/Classifier/fully_connected_2/mul_1_unstack/_191, histogram/h5/Tile_5_unstack)]]
         [[Node: optimizer_loss/train/_202 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2337_optimizer_loss/train", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Exception in thread Thread-2 (most likely raised during interpreter shutdown)```

**Comment by wookayin** [comment]
Thanks for reporting the issue.

Setting the number of CPU threads for op executions (e.g. intra_op_parallelism_threads=1 and inter_op_parallelism_threads=1) will **significantly** impact the performance, which is not recommended. We **must** use object-oriented APIS, for example, `ax.hist` instead of `plt.hist`, because `pyplot` is **NOT** thread-safe (and which is the cause of the error).
